# Generated by Django 3.1.5 on 2021-02-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='content',
            new_name='search',
        ),
    ]
