# Generated by Django 3.1.5 on 2021-02-28 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20210228_0918'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='search_term',
            new_name='search',
        ),
    ]
